### PR TITLE
SQL Server 2016 LocalDB

### PR DESCRIPTION
**Pull request by ramonsmits**
powershel-launcher-download

### CODE REVIEW

**Comment by ramonsmits** [comment]
Works here on a clean 2016 image.

@tmasternak We can also invoke that download directly in the script if we detect that local db is not present. What do you think?

**Comment by ramonsmits** [comment]
Or do something like:

> LocalDB not available, do you want to download the launcher at http://afdsfasdflaskdfj ?

When its done downloading

> Do you want to run the launcher?

**Comment by tmasternak** [comment]
I like the proposal. That would make the whole experience way smoother.

**Comment by ramonsmits** [comment]
I'll make it so :-)

**Comment by tmasternak** [comment]
LGTM

**Pull request merged**
