### PR TITLE
Removed sharing, as instance does not need to be shared between multiple user accounts

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by ramonsmits** [comment]
@mikeminutillo That is weird, that wasn't when I checked in locally. Maybe CRLF? I'll check.

**Comment by tmasternak** [comment]
LocalDB is about sharing between different user accounts. 

@ramonsmits this will work as long as the account that runs the script is the administrator account. Otherwise what can happen is that instance is created by script (on account x) but the processes are running on admin account). Without sharing the admin account will not be able to access the localDB instnace created by the script.

**Comment by ramonsmits** [comment]
@mikeminutillo it was CRLF

**Comment by mikeminutillo** [comment]
I think we should run the entire script elevated. Otherwise we have to prompt for SC, SP, and Monitoring instance which is kind of messy.

**Comment by tmasternak** [comment]
@mikeminutillo agreed. The script is immediately elevated. I missed that. In other words I think we can remove sharing.

**Pull request merged**
